# This is a basic workflow to help you get started with Actions

name: CI/CD for Group 13

# Controls when the workflow will run
on:
  # Triggers the workflow on push events of all branches or pull request events but only for the main branch
  push:
  
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup
        run: npm install

      # Runs testing
      - name: run test suite
        run: npm run test
        
      - name: run jsDoc auto generation
        run: npm run doc

      - name: codecov
        uses: codecov/codecov-action@v2
        with: 
          token: b597cf4e-848f-4367-b5c6-17726b103118
          flags: unittests
