name: Generate JSDocs
on: 
  push:

  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source
          output_dir: ./jsdocs
      
      - name: Add documentation
        uses: EndBug/add-and-commit@v7
        with:
          add: ./jsdocs
          message: 'Update JSDocs'
