name: Generate JSDocs
on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout docs repo
        uses: actions/checkout@v2
        with:
          repository: cse110-fa21-group13/cse110-fa21-group13-docs
          path: docs
          
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source/assets/scripts
          output_dir: docs
      
      - name: Add documentation
        run: |
          cd docs
          git add -A
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "update JSDocs"
          git push https://$USERNAME:$REPO_KEY@github.com/cse110-fa21-group13/cse110-fa21-group13-docs main
          
        env:
          REPO_KEY: ${{ secrets.JSDOCS_TOKEN }}
          USERNAME: github-actions[bot]
